# Generated by Django 6.1 on 2026-08-26 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistName', models.TextField(unique=True)),
                ('place', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'artists',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreName', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langCode', models.TextField(unique=True)),
                ('langName', models.TextField()),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='MyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mytags',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'playlist',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songName', models.TextField()),
                ('album', models.TextField(blank=True, default='')),
                ('year', models.TextField(blank=True, default='')),
                ('songLength', models.TextField(blank=True, default='')),
                ('playCount', models.IntegerField(default=0)),
                ('isrc', models.TextField(blank=True, default='')),
                ('source', models.TextField(default='manual')),
                ('filePath', models.TextField(blank=True, default='')),
                ('addedDate', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'songs',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='SongAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(db_column='album_id', on_delete=django.db.models.deletion.CASCADE, to='songs.album')),
                ('song', models.ForeignKey(db_column='song_id', on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
            ],
            options={
                'db_table': 'song_album',
                'unique_together': {('song', 'album')},
            },
        ),
        migrations.AddField(
            model_name='song',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='songs', through='songs.SongAlbum', to='songs.album'),
        ),
        migrations.CreateModel(
            name='SongArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(default='primary')),
                ('artist', models.ForeignKey(db_column='artist_id', on_delete=django.db.models.deletion.CASCADE, to='songs.artist')),
                ('song', models.ForeignKey(db_column='song_id', on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
            ],
            options={
                'db_table': 'song_artists',
                'unique_together': {('song', 'artist')},
            },
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='songs', through='songs.SongArtist', to='songs.artist'),
        ),
        migrations.CreateModel(
            name='SongGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(db_column='genre_id', on_delete=django.db.models.deletion.CASCADE, to='songs.genre')),
                ('song', models.ForeignKey(db_column='song_id', on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
            ],
            options={
                'db_table': 'song_genres',
                'unique_together': {('song', 'genre')},
            },
        ),
        migrations.AddField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='songs', through='songs.SongGenre', to='songs.genre'),
        ),
        migrations.CreateModel(
            name='SongLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.ForeignKey(db_column='lang_id', on_delete=django.db.models.deletion.CASCADE, to='songs.language')),
                ('song', models.ForeignKey(db_column='song_id', on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
            ],
            options={
                'db_table': 'song_languages',
                'unique_together': {('song', 'lang')},
            },
        ),
        migrations.AddField(
            model_name='song',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='songs', through='songs.SongLanguage', to='songs.language'),
        ),
        migrations.CreateModel(
            name='SongMyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mytag', models.ForeignKey(db_column='mytags', on_delete=django.db.models.deletion.CASCADE, to='songs.mytag')),
                ('song', models.ForeignKey(db_column='song_id', on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
            ],
            options={
                'db_table': 'song_mytags',
                'unique_together': {('song', 'mytag')},
            },
        ),
        migrations.AddField(
            model_name='song',
            name='mytags',
            field=models.ManyToManyField(blank=True, related_name='songs', through='songs.SongMyTag', to='songs.mytag'),
        ),
        migrations.CreateModel(
            name='SongPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(db_column='playlist_id', on_delete=django.db.models.deletion.CASCADE, to='songs.playlist')),
                ('song', models.ForeignKey(db_column='song_id', on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
            ],
            options={
                'db_table': 'song_playlist',
                'unique_together': {('playlist', 'song')},
            },
        ),
        migrations.AddField(
            model_name='song',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='songs', through='songs.SongPlaylist', to='songs.playlist'),
        ),
        migrations.CreateModel(
            name='SongTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagType', models.TextField(default='myTag')),
                ('song', models.ForeignKey(db_column='song_id', on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='songs.tag')),
            ],
            options={
                'db_table': 'song_tags',
                'unique_together': {('song', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='songs', through='songs.SongTag', to='songs.tag'),
        ),
        migrations.CreateModel(
            name='ExternalId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.TextField()),
                ('externalID', models.TextField()),
                ('song', models.ForeignKey(db_column='song_id', on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='songs.song')),
            ],
            options={
                'db_table': 'external_ids',
                'unique_together': {('song', 'platform')},
            },
        ),
    ]
